[package]
name = "iyes_multiplayer_proto_hostauth"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.40"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.serde]
version = "1.0.163"
features = ["derive"]
